export const PATH = {
  HOME: '/',
  SIGNIN: '/signin',
  PARTNERS: '/partners',
  USERS: '/users',
  PROVIDERS: '/providers',
  PARTNER_EKYCS: '/partner-ekycs',
  EKYCS: '/ekycs',
  PROFILE: '/profile',
  DASHBOARD: '/dashboard',
  TRANSACTION: '/transaction',
  FORGOTPASSWORD: '/forgotPassWord',
  RESETPASSWORD: '/resetPassWord',
  VERIFY_ACCOUNT: '/verify-account',
  CHANGE_PASSWORD: '/change-password',
  MAIL: '/mail',
  BALANCE_TRANSACTION: '/balance-transaction',
  DEMO_KEY: '/demo-key',
  ADMIN_MANAGE: '/admin-manage',
  ACCOUNT: '/account',
  BALANCE_PARTNER: '/balance-partner',
  LOG_ERROR: '/log-error',
  ACCOUNT_INFO: '/account/:id'
};
